// eslint-disable-next-line import/no-anonymous-default-export
export default {
    GET_INCOME_DATA: 'GET_INCOME_DATA',
    GET_INCOME_DATA_FAIL: 'GET_INCOME_DATA_FAIL',
    GET_INCOME_DATA_SUCCESS: 'GET_INCOME_DATA_SUCCESS',
    GET_COUNTRY_DATA: 'GET_COUNTRY_DATA',
    GET_COUNTRY_DATA_FAIL: 'GET_COUNTRY_DATA_FAIL',
    GET_COUNTRY_DATA_SUCCESS: 'GET_COUNTRY_DATA_SUCCESS',
    GET_BUYERS_DATA: 'GET_BUYERS_DATA',
    GET_BUYERS_DATA_FAIL: 'GET_BUYERS_DATA_FAIL',
    GET_BUYERS_DATA_SUCCESS: 'GET_BUYERS_DATA_SUCCESS',
    GET_HIGHLIGHTS_DATA: 'GET_HIGHLIGHTS_DATA',
    GET_HIGHLIGHTS_DATA_FAIL: 'GET_HIGHLIGHTS_DATA_FAIL',
    GET_HIGHLIGHTS_DATA_SUCCESS: 'GET_HIGHLIGHTS_DATA_SUCCESS'
}